services:
  - type: web
    name: jsonserver-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
    autoDeploy: true
